FROM cgr.dev/chainguard/busybox:latest@sha256:accc5c911abaf2f70487f93cad07b0891d502cbba7e79f96d1db9074ef40928a

ARG TARGETPLATFORM

COPY ${TARGETPLATFORM}/gasa /usr/bin/gasa

# run as distroless-style nonroot user/group (uid/gid 65532) in final image
USER 65532:65532

# checkov:skip=CKV_DOCKER_2: HEALTHCHECK is not applicable to a CLI-only image
ENTRYPOINT ["/usr/bin/gasa"]
CMD ["--help"]
