FROM cgr.dev/chainguard/busybox:latest@sha256:b225a610a9b461ee2ebaa18ec08d58766d07bba638e6a0fd3cc0d3494bd6c642

ARG TARGETPLATFORM

COPY ${TARGETPLATFORM}/gasa /usr/bin/gasa

# run as distroless-style nonroot user/group (uid/gid 65532) in final image
USER 65532:65532

# checkov:skip=CKV_DOCKER_2: HEALTHCHECK is not applicable to a CLI-only image
ENTRYPOINT ["/usr/bin/gasa"]
CMD ["--help"]
