FROM cgr.dev/chainguard/busybox:latest@sha256:95d25753220528add19b287f2b050397302df56b8b38c4a2d649cd39a7dfb4f9

ARG TARGETPLATFORM

COPY ${TARGETPLATFORM}/gasa /usr/bin/gasa

# run as distroless-style nonroot user/group (uid/gid 65532) in final image
USER 65532:65532

# checkov:skip=CKV_DOCKER_2: HEALTHCHECK is not applicable to a CLI-only image
ENTRYPOINT ["/usr/bin/gasa"]
CMD ["--help"]
