// Command fixtures manages the GitHub repositories the end-to-end suite scans.
//
// The e2e suite asserts what gasa reports about three real repositories. Those
// repositories are inputs to a test, so if they drift the test lies while still
// going green. This command makes their content and settings declarative and
// checked in, so a fixture can be compared against reality, restored, or
// rebuilt from scratch.
//
//	go run ./tools/fixtures verify   # read-only: does reality match the checkout?
//	go run ./tools/fixtures apply    # write: push the checkout back over reality
//	go run ./tools/fixtures capture  # write locally: record reality into the checkout
//
// verify is the only mode CI runs, and the only one the read-only CI token can
// perform. apply and capture are local operations that need an admin token.
package main

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/google/go-github/v84/github"
	"gopkg.in/yaml.v3"
)

const (
	defaultFixturesDir = "testdata/e2e/fixtures"
	manifestName       = "repo.yaml"
	filesDirName       = "files"

	// notApplicable marks a setting GitHub does not offer for this repository,
	// as opposed to one that is simply unset. Private repositories have no
	// fork-PR approval policy at all, and recording that explicitly keeps
	// "absent by design" from looking like "forgot to declare it".
	notApplicable = "n/a"
)

// Manifest is the declarative description of one fixture repository, stored as
// repo.yaml beside the files/ tree it owns.
type Manifest struct {
	Repo    string  `yaml:"repo"`
	Private bool    `yaml:"private"`
	Actions Actions `yaml:"actions"`
	Purpose string  `yaml:"purpose,omitempty"`
	// Unmanaged lists paths this fixture deliberately does not own. Content
	// generated by other tooling lives here: it is left alone by apply and
	// ignored by verify, so a third-party regeneration is not reported as
	// fixture drift.
	Unmanaged []string `yaml:"unmanaged,omitempty"`
}

// Actions mirrors the repository Actions settings the scanner reads. Pointers
// distinguish "declared false" from "not declared".
type Actions struct {
	Enabled                      *bool  `yaml:"enabled"`
	AllowedActions               string `yaml:"allowed_actions"`
	SHAPinningRequired           *bool  `yaml:"sha_pinning_required"`
	DefaultWorkflowPermissions   string `yaml:"default_workflow_permissions"`
	CanApprovePullRequestReviews *bool  `yaml:"can_approve_pull_request_reviews"`
	ForkPRContributorApproval    string `yaml:"fork_pr_contributor_approval"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "\nfixtures: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	mode := ""
	if len(os.Args) > 1 {
		mode = os.Args[1]
	}

	dir := defaultFixturesDir
	if env := os.Getenv("FIXTURES_DIR"); env != "" {
		dir = env
	}

	manifests, err := loadManifests(dir)
	if err != nil {
		return err
	}
	if len(manifests) == 0 {
		return fmt.Errorf("no fixtures found under %s", dir)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	client, err := newClient(ctx)
	if err != nil {
		return err
	}

	switch mode {
	case "verify":
		return verify(ctx, client, manifests)
	case "apply":
		return apply(ctx, client, manifests)
	case "capture":
		return capture(ctx, client, manifests)
	default:
		return fmt.Errorf("usage: fixtures <verify|apply|capture>")
	}
}

// newClient resolves a token the same way the CLI does, so operators do not
// have to think about a second auth mechanism.
func newClient(ctx context.Context) (*github.Client, error) {
	token := os.Getenv("GITHUB_TOKEN")
	if token == "" {
		token = os.Getenv("GH_TOKEN")
	}
	if token == "" {
		token = ghCLIToken(ctx)
	}
	if token == "" {
		return nil, errors.New("no GitHub token found: set GITHUB_TOKEN, GH_TOKEN, or sign in with `gh auth login`")
	}
	return github.NewClient(nil).WithAuthToken(token), nil
}

type fixture struct {
	Manifest
	dir string
}

func loadManifests(dir string) ([]fixture, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read fixtures dir %s: %w", dir, err)
	}

	var out []fixture
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		path := filepath.Join(dir, e.Name(), manifestName)
		raw, err := os.ReadFile(path) //nolint:gosec // path is built from the checked-in fixtures dir
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", path, err)
		}
		var m Manifest
		if err := yaml.Unmarshal(raw, &m); err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}
		if m.Repo == "" {
			return nil, fmt.Errorf("%s: `repo` is required", path)
		}
		out = append(out, fixture{Manifest: m, dir: filepath.Join(dir, e.Name())})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Repo < out[j].Repo })
	return out, nil
}

func splitRepo(full string) (owner, name string, err error) {
	parts := strings.SplitN(full, "/", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", "", fmt.Errorf("repo %q must be owner/name", full)
	}
	return parts[0], parts[1], nil
}

// isUnmanaged reports whether a path is deliberately not owned by the fixture.
// Matching is by exact path or directory prefix, which covers every case the
// fixtures need without inventing a glob dialect.
func (f fixture) isUnmanaged(path string) bool {
	for _, u := range f.Unmanaged {
		if path == u || strings.HasPrefix(path, strings.TrimSuffix(u, "/")+"/") {
			return true
		}
	}
	return false
}

// localFiles returns the fixture's managed tree, keyed by repository path.
func (f fixture) localFiles() (map[string]string, error) {
	root := filepath.Join(f.dir, filesDirName)
	out := make(map[string]string)
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		if f.isUnmanaged(rel) {
			return nil
		}
		content, err := os.ReadFile(path) //nolint:gosec // path comes from walking the checked-in fixtures dir
		if err != nil {
			return err
		}
		out[rel] = string(content)
		return nil
	})
	if errors.Is(err, os.ErrNotExist) {
		return out, nil
	}
	return out, err
}

// remoteFiles returns the repository's managed tree at the default branch.
func remoteFiles(ctx context.Context, client *github.Client, f fixture) (map[string]string, error) {
	owner, name, err := splitRepo(f.Repo)
	if err != nil {
		return nil, err
	}

	repo, _, err := client.Repositories.Get(ctx, owner, name)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", f.Repo, err)
	}

	tree, _, err := client.Git.GetTree(ctx, owner, name, repo.GetDefaultBranch(), true)
	if err != nil {
		return nil, fmt.Errorf("%s: list tree: %w", f.Repo, err)
	}

	out := make(map[string]string)
	for _, entry := range tree.Entries {
		if entry.GetType() != "blob" {
			continue
		}
		path := entry.GetPath()
		if f.isUnmanaged(path) {
			continue
		}
		blob, _, err := client.Git.GetBlob(ctx, owner, name, entry.GetSHA())
		if err != nil {
			return nil, fmt.Errorf("%s: fetch %s: %w", f.Repo, path, err)
		}
		decoded, err := decodeBlob(blob)
		if err != nil {
			return nil, fmt.Errorf("%s: decode %s: %w", f.Repo, path, err)
		}
		out[path] = decoded
	}
	return out, nil
}

// remoteActions reads the Actions settings the scanner cares about. A private
// repository has no fork-PR approval policy, which is recorded as notApplicable
// rather than left blank so the manifest states the fact explicitly.
func remoteActions(ctx context.Context, client *github.Client, f fixture) (Actions, error) {
	owner, name, err := splitRepo(f.Repo)
	if err != nil {
		return Actions{}, err
	}

	var got Actions

	perms, _, err := client.Repositories.GetActionsPermissions(ctx, owner, name)
	if err != nil {
		return got, fmt.Errorf("%s: read actions permissions: %w", f.Repo, err)
	}
	got.Enabled = perms.Enabled
	got.AllowedActions = perms.GetAllowedActions()
	got.SHAPinningRequired = perms.SHAPinningRequired

	workflow, _, err := client.Repositories.GetDefaultWorkflowPermissions(ctx, owner, name)
	if err != nil {
		return got, fmt.Errorf("%s: read workflow permissions: %w", f.Repo, err)
	}
	got.DefaultWorkflowPermissions = workflow.GetDefaultWorkflowPermissions()
	got.CanApprovePullRequestReviews = workflow.CanApprovePullRequestReviews

	policy, resp, err := client.Actions.GetForkPRContributorApprovalPermissions(ctx, owner, name)
	switch {
	case err == nil:
		got.ForkPRContributorApproval = policy.ApprovalPolicy
	case resp != nil && resp.StatusCode == 422:
		got.ForkPRContributorApproval = notApplicable
	default:
		return got, fmt.Errorf("%s: read fork-PR approval: %w", f.Repo, err)
	}

	return got, nil
}

func decodeBlob(blob *github.Blob) (string, error) {
	content := blob.GetContent()
	if blob.GetEncoding() != "base64" {
		return content, nil
	}
	// The blob API wraps base64 at column 60, which the standard decoder rejects.
	decoded, err := base64.StdEncoding.DecodeString(strings.ReplaceAll(content, "\n", ""))
	if err != nil {
		return "", err
	}
	return string(decoded), nil
}

// ghCLIToken borrows the gh CLI's token so local runs need no extra setup, the
// same fallback the scanner itself uses.
func ghCLIToken(ctx context.Context) string {
	out, err := exec.CommandContext(ctx, "gh", "auth", "token").Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}
