name: ci

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# reset permissions to none at the workflow level
# we'll set them at the job level below
permissions: {}

jobs:
  app:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: chainguard-actions/actions-checkout@ec419da8013e66e059571719dbfa6d1483438668 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Go
        uses: chainguard-actions/actions-setup-go@ab5ec24e45be1a7cff2102d2b2e642b5b65813b3 # v7.0.0
        with:
          go-version-file: go.mod

      - name: Test
        run: make test

      - name: Build
        run: make build

  docker:
    runs-on: ubuntu-latest
    needs: app

    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: chainguard-actions/actions-checkout@ec419da8013e66e059571719dbfa6d1483438668 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: chainguard-actions/docker-setup-buildx-action@695a7c62d4fe3f2071dbd659ecd5a8f9bc96e4dd # v4.2.0

      - name: Docker Bake
        run: docker buildx bake
